helium/blockchain-http

.buildkite/env/secrets.ejson, .buildkite/hooks/pre-command, .buildkite/pipeline.yml, .buildkite/scripts/Dockerfile, .buildkite/scripts/lager_console_setup.pl, .buildkite/scripts/make_deb.sh, .buildkite/scripts/make_docker.sh, .buildkite/scripts/packagecloud_upload.sh, Makefile, rebar.config, test/ct/blockchain_http_SUITE.erl
Problem to solve: We want to automatically build blockchain-http deb packages and docker containers.
Solution: Set up buildkite along the same lines as blockchain-etl
=> Add buildkite set up to build packages and docker

.buildkite/scripts/Dockerfile
Problem to solve: The simplest logging solution for `awsvpc` style ECS workloads is printing to the console. During the container build process a script modifies the stock lager configuration to point to the console. As part of PR cleanup the script execution was moved *before* the config file exists, which caused a silent failure.
Solution: Execute the script in the right place.
=> Ensure lager fix runs after software install

rebar.config, rebar.lock, src/bh_db_worker.erl, src/bh_route_accounts.erl, src/bh_route_blocks.erl, src/bh_route_hotspots.erl, src/bh_route_pending_txns.erl, src/bh_route_txns.erl, src/bh_sup.erl
To increase pipelining and to hold the lock on the db connections for
less time, use epgsql's async query support. Additionally do connection
initialization asynchronously to allow the service to start a bit
faster.
Finally, for prepared statements attempt to use the new dispcount
transactions mode that runs a fun that was casted to the worker. This
avoids the caller having to wait for the checkout response and then do a
checkin which should translate to less waiting. We also trick epgsql
into sending the result back to the elli process, not the pool process
which should also improve performance.
=> Use async epqsql functions and dispcount transactions

src/bh_route_blocks.erl, src/bh_route_handler.erl
* Checks for an empty value as an argument and replaces it with the "default" value for the argument
* Actually converts the block height to a number for the blocks routes
=> Validate empty arguments and block height

config/sys.config, src/bh_sup.erl
Makes the read only pool size settable with a `DATABASE_RO_POOL_SIZE` environment variable. Tye sys.config and fallback default are both set to 100 with this change
=> Make read only pool size settable using an environment variable

src/bh_db_worker.erl, src/bh_route_accounts.erl, src/bh_route_blocks.erl, src/bh_route_handler.erl, src/bh_route_handler.hrl, src/bh_route_hotspots.erl, src/bh_route_txns.erl
This PR simplifies the request parameters for paging and introduces a cursor construct to help page through lists of data in a more consistent manner. 
Any route that returns a list will return a `cursor` at the same level as the `data` field which holds the response. The cursor can be used to fetch the next page of data. If a cursor is passed as part of the (uri) request, other arguments are ignored. 
Note that page size, previously configurable via the `limit` argument is no longer exposed. 
The following paged routes are affected:
* `/v1/blocks` - only `before` argument is supported on initial request. Page size is 100
* `/v1/blocks/<height>` - page size for transactions in the block is 50. Each page includes the block. The `transactions` field in the block is the list getting paged. …
=> Improved paging support

src/bh_route_accounts.erl, src/bh_route_txns.erl
Adds support for `/v1/account/<address>/activity`:
* Returns all transactions for the given account 
* Defaults to include all transaction types. You can filter the types of transactions down by passing in a comma separated list of transactions type in the query argument `filter_types`
* Transactions are filtered to subset for activity related to the given account. This means that reward and payment (v2) transactions are filtered down to only include entries related to the given account. 
* Cursor based with a non configuration page size set to 50
Requires: https://github.com/helium/blockchain-etl/pull/33
=> Add account/<x>/activity

src/bh_route_hotspots.erl, src/bh_route_txns.erl
This adds a `/v1/hotspots/<address>/activity` route for hotspots to get a filtered view of all activity related to a given hotspot. 
This first implementation only filters down rewards_v1 transactions for the given hotspot. 
Note that this PR requires https://github.com/helium/blockchain-etl/commit/07b166d5dbdc1958476cf39de8ee6139ba6d6c7f to be deployed on the target database
=> Add hotspot activity route

src/bh_route_accounts.erl, src/bh_route_blocks.erl, src/bh_route_hotspots.erl, src/bh_route_txns.erl, test/bh_route_blocks_SUITE.erl
This PR:
* **Removes** the `transactions` field from `v1/blocks/:height` and `v1/blocks/hash/:hash`. These routes just return the top level block descriptor but is no longer paged since there are no longer any transactions being returned. 
* **Adds** transaction list routes to retrieve paged responses for transactions for a block based on either height or hash. The new routes are:`v1/blocks/:height/transactions` and `v1/blocks/hash/:hash/transactions`
=> Moves transaction for a block to a "transactions" route

config/sys.config, src/bh_route_accounts.erl, src/bh_route_blocks.erl, src/bh_route_elections.erl, src/bh_route_handler.hrl, src/bh_route_hotspots.erl, src/bh_route_txns.erl, src/bh_routes.erl, test/bh_route_elections_SUITE.erl
This adds:
* `/v1/elections` for a paged list of consensus group transactions
* `/v1/hotspots/:address/elections` for a paged list of consensus groups that a given hotspot was involved in 
* `/v1/accounts/:address/elections` for a paged list of consensus groups that all hotspots for a given account were  involved in
=> add election routes

src/bh_route_hotspots.erl
This optimizes out one inner join on the hotspots route since the gateway_ledger now includes the location columns as part of it's materialized view refresh cycle
=> Use hotspot location from gateway_ledger

src/bh_route_hotspots.erl, test/bh_route_accounts_SUITE.erl
This fixes the `/v1/accounts/:address/hotspots` endpoint for accounts with more than 100 hotspots.
=> Fix account hotspot lists with cursor

src/bh_route_accounts.erl, src/bh_route_hotspots.erl, src/bh_route_stats.erl, src/bh_route_txns.erl
Since the defintion of the gateway ledger was changed the
ledger/inventory name change would not have made this switch any
better.
A short outage will occur while upgrading etl and the http front ends.
=> Migrate to inventory tables

src/bh_route_hotspots.erl, src/bh_route_txns.erl
* Adds lat/lon to all challengees in a poc receipt path. This allows applications to show all challengees
* Geocoded the first challengee in poc_receipts paths. This  gives applications a chance to indicate geo information of the starting location of a challenge
=> geo code first challengee in path for poc_receipts

src/bh_route_accounts.erl, test/bh_route_accounts_SUITE.erl
* Adds `v1/accounts/:address/stats` which returns account balance:
* `last_day`: every hour for 24 hours
* `last_week`: every 8 hours for the 7 days
* `last month`: every day for 30 days
=> Add account balance stats

src/bh_route_pending_txns.erl
Since we now allow multiple txns with the same hash we adjust pending
status lookup to use the latest added txn with that hash.
=> Use created_at on pending_txn

src/bh_route_txns.erl
Instead of filtering on actor.block ranges which has multiple actors for the same block use the transaction table to filter block ranges
=> Use transaction table to filter blocks

src/bh_route_accounts.erl
* Account balances were picked as the _maximum_ balance before the bucket end-time which was causing mis-tracked balances for the bucket itself. This picks the _last_ known account balance before the end of the time bucket. 
* In addition the bucket was not inclusive of the current timeframe so would exclude more recent balance changes. This fixes this by including the "next" (partially complete) bucket
=> Fix account balance lookup

src/bh_route_txns.erl
When an actor appears more then once in a transaction the transaction lists returned by various routes could include duplicate transaction entries. This PR fixes this by ensuring distinct transaction hashes
=> attempt distinct txn queries

src/bh_route_pending_txns.erl
Since transactions with the same hash are allowed we inner join pending actors on the created_at date for the transaction
=> join pending_actors with pending_txn on created_at

src/bh_route_txns.erl
Adjust for some json burn transactions still having integer memo fields
=> Convert token_burn memo field to b64

priv/rewards.sql, priv/stats.sql, src/bh_db_worker.erl, src/bh_route_accounts.erl, src/bh_route_hotspots.erl, src/bh_route_rewards.erl, src/bh_route_stats.erl, src/bh_route_vars.erl, test/bh_route_accounts_SUITE.erl, test/bh_route_hotspots_SUITE.erl
This exposes a new rewards/stats route for both accounts and hotspots:
* `/v1/accounts/:address/rewards/stats`
* `/v1/hotspots/:address/rewards/stats`
Both take the following parameters:
* `min_time`: The start time to get statistics for
* `max_time`: The end time to get statistics for
* `bucket`: one of `month`, `week`, `day`, `hour`
The api will bucket the time between min and max_time after _truncating_ their timestamp to the nearest bucket boundary. For each bucket the result includes :
* `timestamp`: the iso8601 timestamp the bucket started at
* `sum`: Total rewards in the bucket
* `avg`: Average rewards in the bucket
* `median`: Median rewards in the bucket
* `stddev`: Standard deviation of rewards in the bucket
* `max`: The maximum reward in the bucket
* `min`: The minimum rewards …
=> Add rewards stats

src/bh_route_hotspots.erl
This _removes_ the `score` and `last_score_block` from the API  as announced in the [engineering blog](https://engineering.helium.com/2020/12/02/helium-api-update-removing-the-score.html)
Fixes #136
=> Remove score from api

priv/hotspots.sql, src/bh_db_worker.erl, src/bh_route_hotspots.erl, test/bh_route_hotspots_SUITE.erl
Expands the `v1/hotspots/elected` route with 
1. `v1/hotspots/elected` - lists "currently elected" hotspots
2. `v1/hotspots/elected/<block>` - lists the elected hotspots that were active at the given block height
3. `v1/hotspost/elected/hash/<hash>` - lists the elected hotspots in the given transaction hash. The transaction identified by the given hash is required to be a `consensus_group_v1`  
Fixes: #145
=> Add election/elected hotspots

config/sys.config, priv/locations.sql, src/bh_route_locations.erl, src/bh_routes.erl, test/bh_route_locations_SUITE.erl
Adds a `v1/locations/:location` that takes an h3 location index and returns geo json.
Fixes #163
=> Add locations route to look up a location

priv/rewards.sql, priv/stats.sql, src/bh_route_accounts.erl, src/bh_route_handler.erl, src/bh_route_hotspots.erl, src/bh_route_rewards.erl, test/bh_route_accounts_SUITE.erl, test/bh_route_hotspots_SUITE.erl
In order to be able to compare stats with other _hotspots_ vs for a single hotspot we need to bucket reward sums by hotspot as well as the time bucket.
This change adds bucketing by hotspot within each time bucket for any route that includes more than one hotspot. i.e. account sum/stats. For a single hotspot the rewards are not bucketed by hotspot but just by time.
We also add a `hotspots/rewards/stats` route which buckets hotspot stats between min/max time and by hotspot within a each bucket.
=> Bucket non hotspot specific sum/stats per hotspot

priv/hotspots.sql, src/bh_route_hotspots.erl, src/bh_route_rewards.erl, test/bh_route_hotspots_SUITE.erl
Introduces a new endpoint `/v1/hotspots/:address/witnesses/sum` to return stats for witnesses for a give hotspot. 
This takes the same min_time, max_time, bucket parameters as the reward sum endpoints, and returns min, max, median, avg, stddev stats for witness counts in each bucket.
Fixes #166
=> Construct hotspot witness statistics

priv/hotspots.sql, src/bh_route_hotspots.erl, test/bh_route_hotspots_SUITE.erl
Adds a `/v1/hotspots/:address/challenges/sums` route which takes `min_time`, `max_tim`, and `bucket` parameters to return a bucketed set of stats for the number of times the given hotspots was a challengee. 
Fixes #172
=> Add challenge bucketed stats

priv/rewards.sql, src/bh_route_rewards.erl, test/bh_route_accounts_SUITE.erl, test/bh_route_hotspots_SUITE.erl, test/ct_utils.erl
This adds a helper to bh_route_rewards to get a full reward list without paging, and a ct_utils helper to walk through an api cursor folding over the paged data.
Fixes #174
=> Fix duplicate rewards in reward cursor paged lists

src/bh_route_accounts.erl, src/bh_route_hotspots.erl, src/bh_route_txns.erl, test/bh_route_accounts_SUITE.erl, test/bh_route_hotspots_SUITE.erl
This adds:
* `/v1/accounts/:address/activity/count` which takes a `filter_types` query parameter and returns a map of counts for the given transaction types
* `/v1/hotspots/:address/activity/count` which takes a `filter_types` query parameter and returns a map of counts for the given transaction types
Fixes: #198
=> Add activity count routes for acccounts/hotspots

priv/hotspots.sql, src/bh_route_hotspots.erl, test/bh_route_hotspots_SUITE.erl
Adds:
`/v1/hotspots/name?search=<term>` which allows searching for hotspots by name.
=> Add name search to hotspot list.

src/bh_route_pending_txns.erl
Return the created_at timestamp for the inserted transaction as part of the json result.
Fixes: #209
=> Add created_at in pending_transaction result

priv/cities.sql, src/bh_route_cities.erl, test/bh_route_cities_SUITE.erl
cities can be ordered by `online_count`, `offline_count`, `hotspot_count` , or long_city name by default.
For example: `/v1/cities?order=online_count` will return all cities with their online hotspot count in descending order
Fixes #207
=> Adds support for `order`

src/bh_route_challenges.erl, src/bh_route_elections.erl, src/bh_route_oracle.erl, src/bh_route_txns.erl, test/bh_route_accounts_SUITE.erl, test/bh_route_hotspots_SUITE.erl
Hotspot/account/oracle activity was searching all the way back to genesis block to try to get a full buffer of transactions to send back even if there were no more to be found. 
This fixes this by locating the earliest block the given actor had a transaction in and limiting the search to that
=> Calculate min block for transaction/activity list

src/bh_route_txns.erl
This fixes activity lists skipping sequences of blocks. 
The bug was introducd when sql limit was used to limit the number of requested results. This caused cursor construction to use the wrong block height.
=> Fix cursor for activity list

priv/oracles.sql, src/bh_route_oracle.erl, test/bh_route_oracle_SUITE.erl
Returns oracle price statistics over a given min/max_time span 
```
http --body get localhost:8080/v1/oracle/prices/stats\?min_time=-30%20day
{
"data": {
"avg": 12.433719079615384,
"max": 20.0,
"median": 12.53731614,
"min": 6.0,
"stddev": 3.50807814
},
"meta": {
"max_time": "2021-04-20T15:52:28Z",
"min_time": "2021-03-21T15:52:28Z"
}
}
```
Fixes: #201
=> Add oracle price stats

src/bh_route_blocks.erl, src/bh_route_handler.erl, src/bh_route_handler.hrl, test/bh_route_blocks_SUITE.erl
This adds a `?max_time` optional query argument for `/v1/blocks/height` to get the height of the chain at a given timestamp. 
e.g. 
```
http --body get localhost:8080/v1/blocks/height\?max_time=2021-03-01
{
"data": {
"height": 741318
},
"meta": {
"max_time": "2021-03-01T00:00:00Z"
}
}
```
Fixes #205
=> Get the block height that was valid at a given UTC time

priv/hotspots.sql, src/bh_route_hotspots.erl
This adds a speculative_nonce  field to /v1/hotspots/:adddress
Fixes #253
=> Add speculative_nonce to single hotspot json

priv/hotspots.sql, src/bh_route_hotspots.erl, test/bh_route_hotspots_SUITE.erl
This adds a lookup for all hotspots in a given h3 index. 
**NOTE** only resolution 8 is supported 
Requires https://github.com/helium/blockchain-etl/pull/169 to be deployed
=> add /v1/hotspots/hex/:h3index

src/bh_route_vars.erl
Maps the `staking_keys_to_mode_mappings` chain variable to a map of public (maker) keys  and corresponding gateway mode
=> Decode mode mappins chain variable to map

priv/hotspots.sql, src/bh_route_hotspots.erl
The ledger information is not tied to the witness time interval being requested so the ledger data was not accurate.
The side effect is what `witness_info` including the rssi table is lost in the witness list (since it was not accurate at all in its counts for the requested block range)
=> use actor table only for PoC witness list

priv/dc_burns.sql, src/bh_route_dc_burns.erl, test/bh_route_dc_burns_SUITE.erl
Adds a `v1/dc_burns/sum` route which can take both bucket and non-bucket time ranges to deliver totals, or bucketed totals for dc_burns
Fixes #275
=> Adds dc_burns sum route

src/bh_route_hotspots.erl
Fixes challenges (bucketed) sum  to only include transactions where the hotspot was a challenger, challengee or witness.
Fixes: #280
=> Fix challenges sum

priv/hotspots.sql, src/bh_route_hotspots.erl
To see how far behind a hotspot is:
Use the `timestamp` field in the status map to query `/v1/blocks/height?max_time=<timestamp>` to get the chain height at that timestamp. Then compare the status height with that chain height for a gap over N blocks.
=> Add status timestamp to hotspot status

priv/hotspots.sql, src/bh_route_hotspots.erl, test/bh_route_hotspots_SUITE.erl
Adds a `hotspots/:address/witnessed` route to return the hotspots that a given hotspot _witnessed_ in the last 5 days
Fixes https://github.com/helium/blockchain-http/issues/284
=> add hotspots/:address/witnessed

config/sys.config, priv/state_channels.sql, src/bh_route_state_channels.erl, src/bh_routes.erl, test/bh_route_state_channels_SUITE.erl
Adds:
* `/v1/state_channels` to list state channel close transaction in descending block order. The results are paginated with a cursor
* `/v1/state_channels/stats` gets the state channels closed in the last 24 hours as a first stat for state channels
Fixes #292
=> Add state_channels endpoint

priv/cities.sql
word similarity goes up when a closer match so list the highest rank first.
Fixes: #309 
Requires: https://github.com/helium/blockchain-etl/pull/220 to get the city search index fixed up
=> Reverse city name search order by rank

src/bh_route_accounts.erl, src/bh_route_assert_locations.erl, src/bh_route_challenges.erl, src/bh_route_elections.erl, src/bh_route_hotspots.erl, src/bh_route_oracle.erl, src/bh_route_state_channels.erl, src/bh_route_txns.erl, src/bh_route_validators.erl, src/bh_route_vars.erl, test/bh_route_hotspots_SUITE.erl
Adds limit query param support for activity/txn list routes in
-  vars (all_activity)
- validators (activity)
- oracle (activity, all_activity)
- hotspots (activity, elections, challenges)
- accounts (activity, challenges, elections)
- assert_locations
- challenges
- elections
- state_channels
Part of improving: #311
=> Add limit request parameter to activity / txn list routes

priv/blocks.sql, priv/rewards.sql, src/bh_route_accounts.erl, src/bh_route_assert_locations.erl, src/bh_route_blocks.erl, src/bh_route_challenges.erl, src/bh_route_elections.erl, src/bh_route_handler.erl, src/bh_route_hotspots.erl, src/bh_route_oracle.erl, src/bh_route_rewards.erl, src/bh_route_state_channels.erl, src/bh_route_txns.erl, src/bh_route_validators.erl, src/bh_route_vars.erl, test/bh_route_accounts_SUITE.erl, test/bh_route_hotspots_SUITE.erl, test/bh_route_validators_SUITE.erl
Add min_time and max_time for ativity/txn list
-  vars (all_activity)
- validators (activity)
- oracle (activity, all_activity)
- hotspots (activity, elections, challenges)
- accounts (activity, challenges, elections)
- assert_locations
- challenges
- elections
- state_channels
Closes #311 
Part of #313
=> Adds min_time, max_time support  to all activity / txn list routes

priv/txns.sql
Use inventory first_block to find first actor activity for accounts, validators, hotspots
Fixes #320
=> Use inventory first_block for activity base block

priv/cities.sql, src/bh_route_cities.erl, test/bh_route_cities_SUITE.erl
* Adds `/v1/cities/:city_id` to return the city for the given city id
* Fixes up city hotspot counts to be integers instead of strings
=> Adds lookup by city id

src/bh_route_pending_txns.erl, src/bh_route_txns.erl
This adds support for transfer_hotspot_v2 transactions
**NOTE** This requires blockchain-etl PR https://github.com/helium/blockchain-etl/pull/250 to be merged and deployed
=> Adds support for transfer_hotspot_v2

priv/vars.sql, src/bh_route_vars.erl, test/bh_route_vars_SUITE.erl
Fixes #348 
on `/v1/vars` you can now pass in a comma separated list of key names to fetch. Max number of keys to request is currently set to 50. You can Keys that do not exist are ignored. 
e.g. 
`/v1/vars?keys=poc_version,securities_percent`
=> Add keys query parameter to vars

priv/vars.sql
Regional parameters are relative large binary entries on chain which can cuase issues for apps/browsers with limited memory since most of them request a full list of chain variables.
Chain variables the begin with region_ are filtered out of the main vars list with this PR. They can still be retrieved if the name of the variable is known using `/var/v1/vars?keys` or `/var/v1/:key`
=> Filters out the large region_ vars

.github/workflows/ci.yml, .github/workflows/package.yml, Dockerfile
Updating default release version of OTP backing HTTP API to v24 for much speed.
=> bumping versions; updating OTP to 24

priv/hotspots.sql
Witnessed query takes too long and cause /hotspots/:address/witnessed API calls to fail. This commit is adding block limiting to the hotspot_witnessed / transaction_actors query. The same limitation is already in place for recent_transactions query.
=> Improve witnessed query performance

priv/hotspots.sql, src/bh_route_hotspots.erl, test/ct_utils.erl
Use blockspan helper to calculate the 5 day low block. 
This should add another speed improvement to https://github.com/helium/blockchain-http/pull/365
=> Use blockspan helper to infer five day window

Makefile
`make start` starts in daemon mode to release the shell prompt. 
Also removing a typo for `rm -rf`
=> Removing a typo in Makefile

src/bh_route_txns.erl
The eequery switchover added explicit atom results to the a number of result columns. This caused binary and atom keys to both be used in initial count construction.
Fixes #380
=> Fix duplicate activity results

.dockerignore
Avoiding sending .git directory into the docker build context
=> adding .git directory to be ignored from docker builds

priv/hotspots.sql, src/bh_route_hotspots.erl
* Reduces witnessed days to the last three days
* Caches witnessed result for 60 blocks (1 hour)
* Optimized query a bit
Fixes #393
=> Update witnessed route

priv/rewards.sql, src/bh_route_accounts.erl, src/bh_route_hotspots.erl, src/bh_route_rewards.erl, test/bh_route_accounts_SUITE.erl, test/bh_route_hotspots_SUITE.erl
This returns the rewards for a given hotspot/account in the given rewards block. 
This requires https://github.com/helium/blockchain-etl/pull/289 to be merged, deployed, and migrations run
=> Add /v1/[accounts|hotspots]/:address/rewards/:block

priv/hotspots.sql, src/bh_route_hotspots.erl
This changes the definition of what it means to be online for a hotspot from confusing peer networkng status to, hopefully, a much simpler “onchain activity” metric.
If a hotspots has any of the following activity in the last 24 hours:
,
* Added
* Rewarded
* a witness
* a challenger
* a challengee
* transited data packets
It is considered to be online.  Otherwise it is considered to be ofline.
Note the slightly questionable use of “a challengee”, since he hotspot in question is not really involved in being a challengee it may not be a good metric. That said it’s the one we have today given how ETL registers changes to the gateway table.
Fixes #389
=> Change definition of online for hotspots

src/bh_route_txns.erl
in receipts_v2 the challenger does _not_ have a location since challenges are generated by validator. This fixes a mismatch in poc_receipts_v2 json generation which would end up excluding the additional decorations (like `location_hex` and `challengee_location_hex`)
=> Fix receipts_v2 mismatch

Dockerfile
See also: https://github.com/helium/blockchain-node/commit/a5edd328d919bf5c698a6dd0c2feb1ef2bb54d3e
=> container runner should match builder version

src/bh_route_handler.erl
As part of the offchain PoC switch a series of witnesses with no asserted location  were allowed onto the chain.
This patch prevents the api from erroring out when this happens.
=> Allow for witness with no location
