src/bh_route_blocks.erl

Includes transactions in block results for single block
requests (height, hash)

Revamp single block routes

---

src/bh_route_hotspots.erl

Adds a field `geocode` to all returned hotspot entries with reverse geocoded information.

Add geocode data to hotspot

---

src/bh_route_txns.erl

Don't merge before SC in core lands

Expose state channel txns

---

src/bh_route_accounts.erl
src/bh_route_txns.erl

This adds support for transactions for an account and general transaction filtering

Add transactions support

---

src/bh_route_blocks.erl
src/bh_route_txns.erl

Adds a time field to all transactions with the time of the transaction (equivalent to block time)

Add transaction time to all txn json

---

src/bh_route_handler.erl
src/bh_route_handler.hrl
src/bh_route_pending_txns.erl

* Adds error handling for an already submitted txn
* Decodes json with maps (regression)

Fix pending_txns endpoint json decoding

---

src/bh_route_blocks.erl

Fixes a missing sql field in block lists

Fix prev hash fetch

---

src/bh_db_worker.erl
src/bh_db_worker.hrl

* Removes unused squery and equery functions
* Increases query timeout for prepared statements to 5 seconds

Adjust db_worker

---

src/bh_route_accounts.erl
src/bh_route_blocks.erl
src/bh_route_challenges.erl
src/bh_route_elections.erl
src/bh_route_handler.erl
src/bh_route_handler.hrl
src/bh_route_hotspots.erl
src/bh_route_txns.erl
test/bh_route_accounts_SUITE.erl
test/bh_route_challenges_SUITE.erl
test/bh_route_elections_SUITE.erl
test/ct_utils.erl

This aligns elections on block range boundaries for query speedup and consistency
Matches: https://github.com/helium/blockchain-http/pull/49

Block aligned elections,challenges feeds

---

src/bh_route_pending_txns.erl

Adds pending_transaction post support.

Add add_gateway and assert_location pending post support

---

src/bh_route_blocks.erl
src/bh_route_txns.erl
test/bh_route_blocks_SUITE.erl

Adds height validation when fetch block transactions

Add block height validation

---

src/bh_route_hotspots.erl
test/bh_route_hotspots_SUITE.erl

Add some test coverage to avoid basic regression

Fix missing hotspots endpoint

---

src/bh_route_stats.erl

Requires ETL to be at least at 1.1.2 to pick up a required function to summarize state channel counts

Add state channel stats for packets and dcs

---

src/bh_route_accounts.erl
src/bh_route_handler.erl
src/bh_route_handler.hrl
src/bh_route_hotspots.erl

This adds json blobs to most error responses.
It also adds a specific ursor expired 400 error response if the cursor
is stale

Add error json to error responses

---

src/bh_route_hotspots.erl

Adds hotspot status to the account/:address/hotspots route. This
includes the sync height as gossiped, an inferred online status and
the gossiped gps fix

Adds owned hotspot status

---

src/bh_route_hotspots.erl

Adds the gateway nonce to account hotspot json

Add gateway nonce

---

src/bh_route_accounts.erl
src/bh_route_blocks.erl
src/bh_route_challenges.erl
src/bh_route_elections.erl
src/bh_route_handler.erl
src/bh_route_handler.hrl
src/bh_route_hotspots.erl
src/bh_route_oracle.erl
src/bh_route_txns.erl
test/bh_route_accounts_SUITE.erl
test/bh_route_challenges_SUITE.erl
test/bh_route_elections_SUITE.erl
test/bh_route_hotspots_SUITE.erl

This makes all txn searches based on overfetching transactions across
increasing block ranges.

Speed Feeds

---

config/sys.config
src/bh_route_handler.hrl
src/bh_route_vars.erl
src/bh_routes.erl
test/bh_route_vars_SUITE.erl

* Adds `/v1/vars` to list all chain vars as a json object
* Adds `/v1/vars/:name` to get the value of a single chain var

Add vars route

---

src/bh_route_vars.erl
test/bh_route_vars_SUITE.erl

Add /v1/vars/activity

---

src/bh_route_txns.erl

In transaction lists that end partway in a block the _rem_ainder of the
txn list is stored in the cursor as the block and the hash of the txn to
start looking from.
The issue was that the remaining transactions in the block were just
inlined on the next request without applying the same filters as the
original request did (actor, owned, and so on).
The fix adds a number of _rem_ queries to fetch the remainder of the
transaction list.

Fix leaking transaction lists

---

src/bh_route_stats.erl

This adds the following json entry to the `/v1/stats` route:
```        
"challenge_counts": {
"active": 1296,
"last_day": 45952
},
```

Add challenge count stats for active/last_day

---

src/bh_route_blocks.erl

Fixes the block list cursor query to not skip blocks

Fix block list before

---

src/bh_route_hotspots.erl
test/bh_route_accounts_SUITE.erl
test/bh_route_cities_SUITE.erl

Increase the hotspot list limit

Try a larger hotspot list size

---

rebar.lock
src/bh_route_pending_txns.erl

Problem to solve: Add the [transfer_hotspot_v1](https://github.com/helium/blockchain-core/pull/659) transaction to the pending transaction route handler.

Add transfer_hotspot_v1 txn to pending transactions

---

src/bh_route_hotspots.erl

Add timestamp_added

---

priv/oracles.sql
rebar.config
src/bh_route_oracle.erl
test/bh_route_oracle_SUITE.erl

Add timestamp to oracle price routes

---

src/bh_route_txns.erl

This adds a transfer_hotspot transaction filter which also enables it to be listed in account activity. 
Fixes: #147

Add transfer_hotspot_v1 filter

---

src/bh_route_vars.erl

Parse hip17 res values into lists of numbers

---

src/bh_route_txns.erl

limit txn searches to a max size

---

priv/hotspots.sql
src/bh_route_hotspots.erl

Requires ETL https://github.com/helium/blockchain-etl/pull/113  to be deployed and migrations  run

Add listen_addrs to hotspot status

---

priv/hotspots.sql

Have hotspot witnesses be a union of all witnesses that witnessed the given hotspot in the last 5 days. 
Requires https://github.com/helium/blockchain-etl/pull/115 to be merged and deployed

Union witnesses

---

src/bh_route_accounts.erl

Remove cursor height restriction

---

priv/hotspots.sql
src/bh_route_hotspots.erl

expose last_poc_challenge for hotspots

---

priv/hotspots.sql
src/bh_route_hotspots.erl

Also fixes a typoo in last_poc_challange
Fixes: #170 
Requires: https://github.com/helium/blockchain-etl/pull/119 to be deployed

Add reward_scale to hotspout output

---

priv/accounts.sql
src/bh_route_accounts.erl
src/bh_route_handler.erl
src/bh_route_handler.hrl
src/bh_route_rewards.erl

Only minor improvement is that min_time and max_time can be omitted to imply "now" in UTC time

Reworks account balance into sql fragments

---

src/bh_route_handler.erl

This change:
* Allows min_time and  max_time to be undefined as query parameters or specified as "now". Both will be interpreted as the current UTC time
* Allows relative times to be specified in hours, days, weeks. For example `..?min_time="-30 day"&max_time="now"` will construct a timespan of the last 30 days. A relative `min_time` is always interpreted relative to `max_time`

Allow min/max time current and relative times

---

priv/ouis.sql
src/bh_route_accounts.erl
src/bh_route_ouis.erl
src/bh_route_pending_txns.erl
test/bh_route_accounts_SUITE.erl
test/bh_route_oui_SUITE.erl

Adds oui routes

---

priv/hotspots.sql

Since a hotspot can be re-asserted, it’s witness list average (currently done over the last 5 days) should be the _greater_ of:
* The last assert_location of the hotspot
* The block height 5 days ago
This PR achieves this
Fixes: #190

Fixes the five day witness averaging

---

src/bh_route_blocks.erl
src/bh_route_cities.erl
src/bh_route_handler.erl
src/bh_route_hotspots.erl
src/bh_route_oracle.erl
src/bh_route_ouis.erl
src/bh_route_pending_txns.erl
test/bh_route_blocks_SUITE.erl
test/bh_route_cities_SUITE.erl
test/bh_route_hotspots_SUITE.erl
test/bh_route_oracle_SUITE.erl
test/bh_route_oui_SUITE.erl

decoded values should ideally return 400s instead of triggering a 500 error.
This adds a helper function and patches a few routes

Adds better error handling around decoded params

---

priv/txns.sql

And use actor table blocks instead of transaction blocks

Group actor source instead of distinct use

---

priv/hotspots.sql
src/bh_route_hotspots.erl

Expose hotspots mode in json

---

src/bh_cache.erl

Problem to solve: We don't have a good idea how many cache hits/misses we have or how long cached answers take to generate. Also we output some log spam when there is no useful information to report.
Solution: Collect some stats about hits and misses, and don't log things when there's nothing useful to report.

Collect some stats on cache hits/misses

---

priv/hotspots.sql
src/bh_route_hotspots.erl

Expose location_hex in hotspot json

---

config/sys.config
priv/accounts.sql
priv/rewards.sql
priv/stats.sql
priv/txns.sql
priv/validators.sql
src/bh_route_accounts.erl
src/bh_route_pending_txns.erl
src/bh_route_rewards.erl
src/bh_route_txns.erl
src/bh_route_validators.erl
src/bh_routes.erl

Adds transaction ingest for stake/unstake_validator and validator stake transfer transactions.

Adds validator transaction ingest

---

src/bh_route_accounts.erl

order rich list by staked_balance + balance

---

priv/hotspots.sql
src/bh_route_hotspots.erl

Adds a `payer` field to hotspot json result

Add hotspot payer field

---

src/bh_route_handler.erl
src/bh_route_hotspots.erl
test/bh_route_hotspots_SUITE.erl

This fixes a cursor issue with hotspot mode filters

Fix up base filter_modes in cursor

---

src/bh_route_assert_locations.erl
src/bh_routes.erl
test/bh_route_assert_locations_SUITE.erl

Add assert_locations route

---

priv/validators.sql
src/bh_route_validators.erl

Adds consensus_groups count to single validator

---

src/bh_route_pending_txns.erl

Distinct on actor based pending_tranactions

---

src/bh_route_txns.erl

Fixes activity for accounts with no activity at all (first block is null)
Fixes #328

Handle account with no activity

---

src/bh_route_rewards.erl

This caches rewards sum results for a long time when both min_time and max_time (and bucket for bucketed sum) are specific as query_params.
This should help with #329 assuming that heavy users (like explorer) use min_time and max_time explicitly and cache the results for use. 
The proposed idea for using this is to collect bucketed sum results on UTC timezone day boundaries (for network earnings in this case), and store those and just ask for a much shorter timeframe from the last stored result to the current time if needed

Cache reward sum results longer

---

priv/dc_burns.sql

This speeds up dc_burn stats queries by using the blocks table height index.

Speed up dc_burn stats

---

src/bh_route_pending_txns.erl
src/bh_route_txns.erl

* init txn type cache for pending since it's in a different connection pool
* correct types for eequery inserts

fix pending eequery types

---

src/bh_route_txns.erl

Fix no result found cache time

---

config/sys.config
src/bh_route_versions.erl
src/bh_routes.erl
test/bh_route_versions_SUITE.erl

Fixes #370 with initial blockchain-http version

Add versions route

---

src/bh_route_hotspots.erl

Fixes mis decoding filter_modes argument in hotspot routes.
Fixes #404

Fix hotspot filter mode issues

---

priv/accounts.sql
src/bh_route_accounts.erl

Add hotspot and validator counts to account details

---

priv/challenges.sql
rebar.config
rebar.lock
src/bh_route_challenges.erl
src/bh_route_txns.erl

NOTE: Requires helium_proto branch merge before merging up!

Add poc_receipts_v2 support

---

priv/accounts.sql
src/bh_route_accounts.erl

Adds account balance and account stats support for iot and mobile tokens

add subnetwork balance support
